### ISSUE TITLE
Improve ease of installation, remove copied JavaScript code

### ISSUE THREAD

**Issue by pysailor** [plone/plone.patternslib#10]
We want this package to become easier to simply use as an add-on for Plone. And, we want to remove all the duplicated code that is available in Patternslib and elsewhere.

Therefore, as @pilz and me have tried to outline on the [wiki](https://github.com/plone/plone.patternslib/wiki), an integrator who wants to use this package should only need to add it to the buildout and install it.

Also, we think everything should be compiled into one single bundle. That means additional dependencies like pat-leaflet should also be part of the patterns-compiled.js.

On the other hand, it should not be necessary to keep a copy of the code (Patternslib, pat-leaflet) etc in this repository, since we can define our dependencies and pinnings via bower.
Any developer who wants to update the bundle would go into src/plone/patternslib/static and run the necessary npm and bower commands. For convenience, there's a Makefile that provides `make bundle`. 
But the JavaScript resources that will be fetched for this are not added to this repo.

We have started to rework this package as described above in branch "update-ploneconf". For our use-cases, this seems to be fine.

@thet since you were active on this package, can you please take a look if that approach would still fit your requirements and workflow? Especially regarding the resource registry, since we have never used the built-in development mode or Build button - maybe that would be broken now.

**Comment by thet** [comment]
As discussed @ ploneconf, IMO the resources in this repository are necessary. Some of them overload resources otherwise registered by Plone itself, but here they are included in a newer version (pat-registry, etc.).
And all the individual pattern registrations make it easy to depend on them in a custom bundle, thus just including those which are actually needed.

Still, plone.patternslib provides the ``patterns`` bundle as well as a ``bundle-leaflet`` bundle - both of them usable out of the box by just installing the package (and adding appropriate trigger-classes to the html).

IMO, this issue could be closed - otherwise let's continue the discussion.

**Comment by petschki** [comment]
This package is obsolete since Plone 6.
